dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - sudo ln -s $(type -P node) /usr/bin/node
  - cd judger
  - sudo chmod +x install-chroot.sh
  - sudo ./install-chroot.sh
install:
  - sudo $(which npm) --version
  - sudo $(which npm) install
script:
  - sudo $(which npm) run test-sandbox