dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - cd judger
  - sudo chmod +x install-chroot.sh
  - sudo ./install-chroot.sh
install:
  - sudo npm install
script:
  - sudo npm run test-sandbox